create schema if not exists auth;

create table if not exists auth.refresh_tokens(
    id int generated by default as identity primary key,
    user_email varchar not null,
    token varchar not null,
    expiry_date timestamp not null
);